In [2]:
import pandas as pd
import numpy as np
data_train = pd.read_csv(r"C:\Users\sande\OneDrive\Desktop\car_insurance_data\train.csv")
data_train.head(2)

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0


In [3]:
data_train.shape

(58592, 44)

In [4]:
import pandas as pd
import numpy as np
data_test = pd.read_csv(r"C:\Users\sande\OneDrive\Desktop\car_insurance_data\test.csv")
data_test.shape

(39063, 43)

In [5]:
data_train.columns

Index(['policy_id', 'policy_tenure', 'age_of_car', 'age_of_policyholder',
       'area_cluster', 'population_density', 'make', 'segment', 'model',
       'fuel_type', 'max_torque', 'max_power', 'engine_type', 'airbags',
       'is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'gear_box', 'steering_type', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'is_front_fog_lights',
       'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks',
       'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating', 'is_claim'],
      dtype='object')

In [6]:
data_test.columns

Index(['policy_id', 'policy_tenure', 'age_of_car', 'age_of_policyholder',
       'area_cluster', 'population_density', 'make', 'segment', 'model',
       'fuel_type', 'max_torque', 'max_power', 'engine_type', 'airbags',
       'is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'gear_box', 'steering_type', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'is_front_fog_lights',
       'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks',
       'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating'],
      dtype='object')

In [7]:
data_train.isna().sum()

policy_id                           0
policy_tenure                       0
age_of_car                          0
age_of_policyholder                 0
area_cluster                        0
population_density                  0
make                                0
segment                             0
model                               0
fuel_type                           0
max_torque                          0
max_power                           0
engine_type                         0
airbags                             0
is_esc                              0
is_adjustable_steering              0
is_tpms                             0
is_parking_sensors                  0
is_parking_camera                   0
rear_brakes_type                    0
displacement                        0
cylinder                            0
transmission_type                   0
gear_box                            0
steering_type                       0
turning_radius                      0
length      

In [8]:
data_test.isna().sum()

policy_id                           0
policy_tenure                       0
age_of_car                          0
age_of_policyholder                 0
area_cluster                        0
population_density                  0
make                                0
segment                             0
model                               0
fuel_type                           0
max_torque                          0
max_power                           0
engine_type                         0
airbags                             0
is_esc                              0
is_adjustable_steering              0
is_tpms                             0
is_parking_sensors                  0
is_parking_camera                   0
rear_brakes_type                    0
displacement                        0
cylinder                            0
transmission_type                   0
gear_box                            0
steering_type                       0
turning_radius                      0
length      

In [9]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   policy_id                         58592 non-null  object 
 1   policy_tenure                     58592 non-null  float64
 2   age_of_car                        58592 non-null  float64
 3   age_of_policyholder               58592 non-null  float64
 4   area_cluster                      58592 non-null  object 
 5   population_density                58592 non-null  int64  
 6   make                              58592 non-null  int64  
 7   segment                           58592 non-null  object 
 8   model                             58592 non-null  object 
 9   fuel_type                         58592 non-null  object 
 10  max_torque                        58592 non-null  object 
 11  max_power                         58592 non-null  object 
 12  engi

In [10]:
data_train['policy_id'].nunique()
# data_train['policy_id'].dtype

58592

In [11]:
data_test['policy_id'].nunique()

39063

In [12]:
data_train['policy_id'].unique()

array(['ID00001', 'ID00002', 'ID00003', ..., 'ID58590', 'ID58591',
       'ID58592'], shape=(58592,), dtype=object)

In [13]:
data_train = data_train.drop('policy_id',axis=1)

In [14]:
data_test = data_test.drop('policy_id',axis=1)

In [15]:
data_train.shape

(58592, 43)

In [16]:
data_train['policy_tenure'].nunique()

58592

In [17]:
data_train['policy_tenure'].unique()

array([0.51587359, 0.67261851, 0.84111026, ..., 1.16227251, 1.2363069 ,
       0.12442893], shape=(58592,))

In [18]:
data_test['policy_tenure'].unique()

array([0.34173168, 0.30724144, 0.32792377, ..., 0.52028737, 1.17239103,
       0.09403029], shape=(39063,))

In [19]:
data_train['policy_tenure'].describe()

count    58592.000000
mean         0.611246
std          0.414156
min          0.002735
25%          0.210250
50%          0.573792
75%          1.039104
max          1.396641
Name: policy_tenure, dtype: float64

In [20]:
data_test['policy_tenure'].describe()

count    39063.000000
mean         0.611304
std          0.415005
min          0.002745
25%          0.208958
50%          0.574078
75%          1.040936
max          1.391398
Name: policy_tenure, dtype: float64

In [21]:
data_train['age_of_car'].nunique()

49

In [22]:
data_test['age_of_car'].nunique()

51

In [23]:
data_train['age_of_car'].isna().sum()

np.int64(0)

In [24]:
data_train['age_of_car'].describe()

count    58592.000000
mean         0.069424
std          0.056721
min          0.000000
25%          0.020000
50%          0.060000
75%          0.110000
max          1.000000
Name: age_of_car, dtype: float64

In [25]:
data_test['age_of_car'].describe()

count    39063.000000
mean         0.069635
std          0.056854
min          0.000000
25%          0.020000
50%          0.060000
75%          0.110000
max          1.000000
Name: age_of_car, dtype: float64

In [26]:
data_train['age_of_policyholder'].nunique()

75

In [27]:
data_test['age_of_policyholder'].nunique()

72

In [28]:
data_train['age_of_policyholder'].describe()

count    58592.000000
mean         0.469420
std          0.122886
min          0.288462
25%          0.365385
50%          0.451923
75%          0.548077
max          1.000000
Name: age_of_policyholder, dtype: float64

In [29]:
data_test['age_of_policyholder'].describe()

count    39063.000000
mean         0.469087
std          0.122072
min          0.288462
25%          0.375000
50%          0.451923
75%          0.548077
max          0.990385
Name: age_of_policyholder, dtype: float64

In [30]:
data_train['age_of_policyholder'].isna().sum()

np.int64(0)

In [31]:
data_test['age_of_policyholder'].isna().sum()

np.int64(0)

In [32]:
data_train['area_cluster'].unique()

array(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11',
       'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20',
       'C21', 'C22'], dtype=object)

In [33]:
data_test['area_cluster'].unique()

array(['C3', 'C8', 'C5', 'C16', 'C14', 'C11', 'C2', 'C1', 'C9', 'C15',
       'C10', 'C19', 'C13', 'C6', 'C4', 'C12', 'C18', 'C7', 'C22', 'C17',
       'C20', 'C21'], dtype=object)

In [34]:
data_train['area_cluster'].isna().sum()

np.int64(0)

In [35]:
data_test['area_cluster'].isna().sum()

np.int64(0)

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data_train['area_cluster'] = le.fit_transform(data_train['area_cluster'])

In [37]:
data_test['area_cluster'] = le.fit_transform(data_test['area_cluster'])

In [38]:
data_train['area_cluster'].unique()

array([ 0, 11, 15, 16, 17, 18, 19, 20, 21,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 12, 13, 14])

In [39]:
data_test['area_cluster'].unique()

array([15, 20, 17,  7,  5,  2, 11,  0, 21,  6,  1, 10,  4, 18, 16,  3,  9,
       19, 14,  8, 12, 13])

In [40]:
data_train['population_density'].unique()

array([ 4990, 27003,  4076, 21622, 34738, 13051,  6112,  8794, 17804,
       73430,  6108, 34791,  5410,  7788,   290, 16206, 65567, 35036,
       27742, 20905,  3264, 16733])

In [41]:
data_test['population_density'].unique()

array([ 4076,  8794, 34738, 16206,  7788,  6108, 27003,  4990, 17804,
         290, 73430, 27742,  5410, 13051, 21622, 34791, 35036,  6112,
       16733, 65567, 20905,  3264])

In [42]:
data_test['population_density'].isna().sum()

np.int64(0)

In [43]:
data_train['population_density'].dtype

dtype('int64')

In [44]:
data_test['population_density'].dtype

dtype('int64')

In [45]:
data_train['population_density'].describe()

count    58592.000000
mean     18826.858667
std      17660.174792
min        290.000000
25%       6112.000000
50%       8794.000000
75%      27003.000000
max      73430.000000
Name: population_density, dtype: float64

In [46]:
data_test['population_density'].describe()

count    39063.000000
mean     18816.232496
std      17651.942351
min        290.000000
25%       6112.000000
50%       8794.000000
75%      27003.000000
max      73430.000000
Name: population_density, dtype: float64

In [47]:
data_train['make'].unique()

array([1, 2, 3, 4, 5])

In [48]:
data_test['make'].unique()

array([1, 2, 3, 4, 5])

In [49]:
# data_train['make'].isna().sum()
# data_train['make'].dtypes
# data_train['make'].describe()
data_train.drop(columns=['make'], inplace=True)

In [50]:
data_test.drop(columns=['make'], inplace=True)

In [51]:
data_train['segment'].unique()

array(['A', 'C1', 'C2', 'B2', 'B1', 'Utility'], dtype=object)

In [52]:
data_test['segment'].unique()

array(['A', 'B2', 'B1', 'C2', 'C1', 'Utility'], dtype=object)

In [53]:
data_train['segment'].value_counts()

segment
B2         18314
A          17321
C2         14018
B1          4173
C1          3557
Utility     1209
Name: count, dtype: int64

In [54]:
data_test['segment'].value_counts()

segment
B2         12049
A          11690
C2          9365
B1          2894
C1          2340
Utility      725
Name: count, dtype: int64

In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data_train['segment'] = le.fit_transform(data_train['segment'])

In [56]:
data_test['segment'] = le.fit_transform(data_test['segment'])

In [57]:
data_test['segment'].unique()

array([0, 2, 1, 4, 3, 5])

In [58]:
data_train['segment'].unique()

array([0, 3, 4, 2, 1, 5])

In [59]:
data_train['model'].unique()

array(['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11'],
      dtype=object)

In [60]:
data_test['model'].unique()

array(['M1', 'M6', 'M3', 'M7', 'M8', 'M4', 'M5', 'M9', 'M2', 'M11', 'M10'],
      dtype=object)

In [61]:
data_train.drop(columns=['model'], inplace=True)

In [62]:
data_test.drop(columns=['model'], inplace=True)

In [63]:
data_train['fuel_type'].unique()

array(['CNG', 'Petrol', 'Diesel'], dtype=object)

In [64]:
data_test['fuel_type'].unique()

array(['CNG', 'Petrol', 'Diesel'], dtype=object)

In [65]:
mapping ={
    'CNG':0,'Petrol':1,'Diesel':2
}
data_train['fuel_type'] = data_train['fuel_type'].map(mapping)

In [66]:
data_test['fuel_type'] = data_test['fuel_type'].map(mapping)

In [67]:
data_train['fuel_type'].unique()

array([0, 1, 2])

In [68]:
data_train['max_torque'].unique()

array(['60Nm@3500rpm', '113Nm@4400rpm', '91Nm@4250rpm', '250Nm@2750rpm',
       '200Nm@3000rpm', '82.1Nm@3400rpm', '200Nm@1750rpm', '85Nm@3000rpm',
       '170Nm@4000rpm'], dtype=object)

In [69]:
data_test['max_torque'].unique()

array(['60Nm@3500rpm', '113Nm@4400rpm', '91Nm@4250rpm', '82.1Nm@3400rpm',
       '250Nm@2750rpm', '200Nm@3000rpm', '200Nm@1750rpm', '170Nm@4000rpm',
       '85Nm@3000rpm'], dtype=object)

In [70]:
data_train['max_torque'] = (
    data_train['max_torque']
    .str.extract(r'([\d\.]+)')
    .astype(float)
)

In [71]:
data_test['max_torque'] = (
    data_test['max_torque']
    .str.extract(r'([\d\.]+)')
    .astype(float)
)

In [72]:
data_train['max_torque'].unique()

array([ 60. , 113. ,  91. , 250. , 200. ,  82.1,  85. , 170. ])

In [73]:
data_test['max_torque'].unique()

array([ 60. , 113. ,  91. ,  82.1, 250. , 200. , 170. ,  85. ])

In [74]:
data_train['max_power'].unique()

array(['40.36bhp@6000rpm', '88.50bhp@6000rpm', '67.06bhp@5500rpm',
       '113.45bhp@4000rpm', '88.77bhp@4000rpm', '55.92bhp@5300rpm',
       '97.89bhp@3600rpm', '61.68bhp@6000rpm', '118.36bhp@5500rpm'],
      dtype=object)

In [75]:
data_test['max_power'].unique()

array(['40.36bhp@6000rpm', '88.50bhp@6000rpm', '67.06bhp@5500rpm',
       '55.92bhp@5300rpm', '113.45bhp@4000rpm', '88.77bhp@4000rpm',
       '97.89bhp@3600rpm', '118.36bhp@5500rpm', '61.68bhp@6000rpm'],
      dtype=object)

In [76]:
data_train['max_power'] = (
    data_train['max_power']
    .str.extract(r'([\d\.]+)')
    .astype(float)
)

In [77]:
data_test['max_power'] = (
    data_test['max_power']
    .str.extract(r'([\d\.]+)')
    .astype(float)
)

In [78]:
data_train['engine_type'].unique()

array(['F8D Petrol Engine', '1.2 L K12N Dualjet', '1.0 SCe',
       '1.5 L U2 CRDi', '1.5 Turbocharged Revotorq', 'K Series Dual jet',
       '1.2 L K Series Engine', 'K10C', 'i-DTEC', 'G12B',
       '1.5 Turbocharged Revotron'], dtype=object)

In [79]:
data_test['engine_type'].unique()

array(['F8D Petrol Engine', 'K Series Dual jet', '1.0 SCe',
       '1.2 L K Series Engine', 'K10C', '1.5 L U2 CRDi',
       '1.5 Turbocharged Revotorq', 'i-DTEC', '1.2 L K12N Dualjet',
       '1.5 Turbocharged Revotron', 'G12B'], dtype=object)

In [80]:
data_train.drop(columns=['engine_type'], inplace=True)

In [81]:
data_test.drop(columns=['engine_type'], inplace=True)

In [82]:
data_train['airbags'].unique()

array([2, 6, 1])

In [83]:
data_test['airbags'].unique()

array([2, 6, 1])

In [84]:
data_train['is_esc'].unique()

array(['No', 'Yes'], dtype=object)

In [85]:
data_test['is_esc'].unique()

array(['No', 'Yes'], dtype=object)

In [86]:
common_map = {
    'No' :0,'Yes':1
}
data_test['is_esc'] = data_test['is_esc'].map(common_map)
data_train['is_esc'] = data_train['is_esc'].map(common_map)

In [87]:
data_train['is_adjustable_steering'].unique()

array(['No', 'Yes'], dtype=object)

In [88]:
data_test['is_adjustable_steering'].unique()

array(['No', 'Yes'], dtype=object)

In [89]:
data_test['is_adjustable_steering'] = data_test['is_adjustable_steering'].map(common_map)
data_train['is_adjustable_steering'] = data_train['is_adjustable_steering'].map(common_map)

In [90]:
data_test['is_tpms'].unique()

array(['No', 'Yes'], dtype=object)

In [91]:
data_train['is_tpms'].unique()

array(['No', 'Yes'], dtype=object)

In [92]:
data_test['is_tpms'] = data_test['is_tpms'].map(common_map)
data_train['is_tpms'] = data_train['is_tpms'].map(common_map)

In [93]:
data_train['is_parking_sensors'].unique()

array(['Yes', 'No'], dtype=object)

In [94]:
data_test['is_parking_sensors'].unique()

array(['Yes', 'No'], dtype=object)

In [95]:
data_test['is_parking_sensors'] = data_test['is_parking_sensors'].map(common_map)
data_train['is_parking_sensors'] = data_train['is_parking_sensors'].map(common_map)

In [96]:
data_test['is_parking_camera'].unique()

array(['No', 'Yes'], dtype=object)

In [97]:
data_train['is_parking_camera'].unique()

array(['No', 'Yes'], dtype=object)

In [98]:
data_test['is_parking_camera'] = data_test['is_parking_camera'].map(common_map)
data_train['is_parking_camera'] = data_train['is_parking_camera'].map(common_map)

In [99]:
data_train['rear_brakes_type'].unique()

array(['Drum', 'Disc'], dtype=object)

In [100]:
data_test['rear_brakes_type'].unique()

array(['Drum', 'Disc'], dtype=object)

In [101]:
# rear_map ={
#     'Drum': 0 , 'Disc': 1
# }
# data_test['rear_brakes_type'] = data_test['rear_brakes_type'].map(rear_map)
# data_train['rear_brakes_type'] = data_train['rear_brakes_type'].map(rear_map)

In [102]:
data_train.drop(columns=['rear_brakes_type'], inplace=True)
data_test.drop(columns=['rear_brakes_type'], inplace = True)

In [103]:
data_test['displacement'].unique()

array([ 796, 1197,  999,  998, 1493, 1497, 1498, 1199, 1196])

In [104]:
data_train['displacement'].unique()

array([ 796, 1197,  999, 1493, 1497,  998, 1498, 1196, 1199])

In [105]:
data_train['cylinder'].unique()

array([3, 4])

In [106]:
data_test['cylinder'].unique()

array([3, 4])

In [107]:
data_train.drop(columns=['cylinder'], inplace=True)
data_test.drop(columns=['cylinder'], inplace = True)

In [108]:
data_test['transmission_type'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [109]:
data_train['transmission_type'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [110]:
trans_map={
    'Manual': 0 , 'Automatic':1   
}
data_train['transmission_type'] = data_train['transmission_type'].map(trans_map)
data_test['transmission_type'] = data_test['transmission_type'].map(trans_map)

In [111]:
data_test['gear_box'].unique()

array([5, 6])

In [112]:
data_train['gear_box'].unique()

array([5, 6])

In [113]:
data_train.drop(columns=['gear_box'], inplace=True)
data_test.drop(columns=['gear_box'], inplace = True)

In [114]:
data_train['steering_type'].unique()

array(['Power', 'Electric', 'Manual'], dtype=object)

In [115]:
data_test['steering_type'].unique()

array(['Power', 'Electric', 'Manual'], dtype=object)

In [116]:
# str_map ={
#     'Power': 0, 'Electric':1, 'Manual':2
# }
# data_test['steering_type'] = data_test['steering_type'].map(str_map)
# data_train['steering_type'] = data_train['steering_type'].map(str_map)
data_train.drop(columns=['steering_type'], inplace=True)
data_test.drop(columns=['steering_type'], inplace = True)

In [117]:
data_test['turning_radius'].unique()

array([4.6 , 4.8 , 5.  , 4.85, 4.7 , 5.2 , 4.9 , 5.1 , 4.5 ])

In [118]:
data_test['turning_radius'].dtype

dtype('float64')

In [119]:
data_train['turning_radius'].unique()

array([4.6 , 4.8 , 5.  , 5.2 , 4.85, 4.7 , 4.9 , 4.5 , 5.1 ])

In [120]:
data_train['length'].unique()

array([3445, 3995, 3731, 4300, 3990, 3845, 3655, 3675, 3993])

In [121]:
data_test['length'].unique()

array([3445, 3845, 3731, 3990, 3655, 4300, 3995, 3993, 3675])

In [122]:
data_test['width'].unique()

array([1515, 1735, 1579, 1745, 1620, 1790, 1755, 1695, 1811, 1475])

In [123]:
data_train['width'].unique()

array([1515, 1735, 1579, 1790, 1755, 1745, 1620, 1695, 1475, 1811])

In [124]:
data_test['height'].unique()

array([1475, 1530, 1490, 1500, 1675, 1635, 1523, 1501, 1515, 1606, 1825])

In [125]:
data_train['height'].unique()

array([1475, 1515, 1490, 1635, 1523, 1530, 1500, 1675, 1501, 1825, 1606])

In [126]:
data_test['gross_weight'].unique()

array([1185, 1335, 1155, 1410, 1340, 1720, 1490, 1051, 1660, 1510])

In [127]:
data_test['is_front_fog_lights'].unique()

array(['No', 'Yes'], dtype=object)

In [128]:
data_train['is_front_fog_lights'].unique()

array(['No', 'Yes'], dtype=object)

In [129]:
data_test['is_front_fog_lights'] = data_test['is_front_fog_lights'].map(common_map)
data_train['is_front_fog_lights'] = data_train['is_front_fog_lights'].map(common_map)

In [130]:
data_train['is_rear_window_wiper'].unique()

array(['No', 'Yes'], dtype=object)

In [131]:
data_test['is_rear_window_wiper'] = data_test['is_rear_window_wiper'].map(common_map)
data_train['is_rear_window_wiper'] = data_train['is_rear_window_wiper'].map(common_map)

In [132]:
data_train['is_rear_window_washer'].unique()

array(['No', 'Yes'], dtype=object)

In [133]:
data_test['is_rear_window_defogger'].unique()

array(['No', 'Yes'], dtype=object)

In [134]:
data_test['is_brake_assist'].unique()

array(['No', 'Yes'], dtype=object)

In [135]:
data_train['is_power_door_locks'].unique()

array(['No', 'Yes'], dtype=object)

In [136]:
data_train['is_central_locking'].unique()

array(['No', 'Yes'], dtype=object)

In [137]:
data_train['is_power_steering'].unique()

array(['Yes', 'No'], dtype=object)

In [138]:
data_train['is_driver_seat_height_adjustable'].unique()

array(['No', 'Yes'], dtype=object)

In [139]:
data_train['is_day_night_rear_view_mirror'].unique()

array(['No', 'Yes'], dtype=object)

In [140]:
data_train['is_ecw'].unique()

array(['No', 'Yes'], dtype=object)

In [141]:
data_train['is_speed_alert'].unique()

array(['Yes', 'No'], dtype=object)

In [142]:
data_train['ncap_rating'].unique()

array([0, 2, 3, 5, 4])

In [143]:
common_map = {'No': 0, 'Yes': 1}

binary_cols = [
    'is_rear_window_washer',
    'is_rear_window_defogger',
    'is_brake_assist',
    'is_power_door_locks',
    'is_central_locking',
    'is_power_steering',
    'is_driver_seat_height_adjustable',
    'is_day_night_rear_view_mirror',
    'is_ecw',
    'is_speed_alert'
]

for col in binary_cols:
    data_train[col] = data_train[col].map(common_map)
    data_test[col] = data_test[col].map(common_map)

In [144]:
drop_cols = [
    'turning_radius',
    'length','width','height',
    'is_power_door_locks',
    'is_central_locking',
    'is_power_steering',
    'is_driver_seat_height_adjustable',
    'is_day_night_rear_view_mirror'
]

data_train.drop(columns=drop_cols, inplace=True)
data_test.drop(columns=drop_cols, inplace=True)

In [145]:
data_train.shape

(58592, 27)

In [202]:
data_train.columns

Index(['policy_tenure', 'age_of_car', 'age_of_policyholder', 'area_cluster',
       'population_density', 'segment', 'fuel_type', 'max_torque', 'max_power',
       'airbags', 'is_esc', 'is_adjustable_steering', 'is_tpms',
       'is_parking_sensors', 'is_parking_camera', 'displacement',
       'transmission_type', 'gross_weight', 'is_front_fog_lights',
       'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_ecw',
       'is_speed_alert', 'ncap_rating', 'is_claim'],
      dtype='object')

In [146]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   policy_tenure            58592 non-null  float64
 1   age_of_car               58592 non-null  float64
 2   age_of_policyholder      58592 non-null  float64
 3   area_cluster             58592 non-null  int64  
 4   population_density       58592 non-null  int64  
 5   segment                  58592 non-null  int64  
 6   fuel_type                58592 non-null  int64  
 7   max_torque               58592 non-null  float64
 8   max_power                58592 non-null  float64
 9   airbags                  58592 non-null  int64  
 10  is_esc                   58592 non-null  int64  
 11  is_adjustable_steering   58592 non-null  int64  
 12  is_tpms                  58592 non-null  int64  
 13  is_parking_sensors       58592 non-null  int64  
 14  is_parking_camera     

In [147]:
data_train['is_claim'].unique()

array([0, 1])

In [148]:
data_train['is_claim'].value_counts()

is_claim
0    54844
1     3748
Name: count, dtype: int64

In [149]:
X = data_train.drop('is_claim', axis=1)
y = data_train['is_claim']

In [150]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [151]:
num_cols = [
    'policy_tenure',
    'age_of_car',
    'age_of_policyholder',
    'population_density',
    'displacement',
    'gross_weight',
    'max_power',
    'max_torque'
]

In [152]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_val[num_cols]   = scaler.transform(X_val[num_cols])
data_test[num_cols] = scaler.transform(data_test[num_cols])

In [153]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

In [154]:
# from sklearn.linear_model import LogisticRegression

# model_log = LogisticRegression()
# model_log.fit(X_train, y_train_sm)
from sklearn.linear_model import LogisticRegression

model_log = LogisticRegression(max_iter=1000)
model_log.fit(X_train_sm, y_train_sm)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [155]:
y_val_pred = model_log.predict(X_val)

In [156]:
y_val_prob = model_log.predict_proba(X_val)[:, 1]
y_val_prob

array([0.58975501, 0.31164713, 0.52028956, ..., 0.47325164, 0.53049163,
       0.70538362], shape=(11719,))

In [157]:
test_preds = model_log.predict(data_test)
test_probs = model_log.predict_proba(data_test)[:, 1]

In [158]:
from sklearn.metrics import (precision_score,recall_score,f1_score,accuracy_score,confusion_matrix,roc_auc_score)
precision = precision_score(y_val, y_val_pred)
recall    = recall_score(y_val, y_val_pred)
f1        = f1_score(y_val, y_val_pred)
accuracy  = accuracy_score(y_val, y_val_pred)
conf_mat  = confusion_matrix(y_val, y_val_pred)
roc_auc   = roc_auc_score(y_val, y_val_prob)

print("Precision :", precision)
print("Recall    :", recall)
print("F1 Score  :", f1)
print("Accuracy  :", accuracy)
print("ROC-AUC   :", roc_auc)
print("Confusion Matrix:\n", conf_mat)

Precision : 0.08098039215686274
Recall    : 0.5506666666666666
F1 Score  : 0.14119658119658118
Accuracy  : 0.5712944790511135
ROC-AUC   : 0.5876679126021819
Confusion Matrix:
 [[6282 4687]
 [ 337  413]]


In [159]:
from sklearn.linear_model import LogisticRegression

model_log1 = LogisticRegression( max_iter=1000,class_weight='balanced')
model_log1.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,'balanced'
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [160]:
y_val_pred1 = model_log1.predict(X_val)

In [161]:
y_val_prob1 = model_log1.predict_proba(X_val)[:, 1]


In [162]:
test_preds1 = model_log1.predict(data_test)
test_probs1 = model_log1.predict_proba(data_test)[:, 1]

In [163]:
from sklearn.metrics import (precision_score,recall_score,f1_score,accuracy_score,confusion_matrix,roc_auc_score)
precision = precision_score(y_val, y_val_pred1)
recall    = recall_score(y_val, y_val_pred1)
f1        = f1_score(y_val, y_val_pred1)
accuracy  = accuracy_score(y_val, y_val_pred1)
conf_mat  = confusion_matrix(y_val, y_val_pred1)
roc_auc   = roc_auc_score(y_val, y_val_prob1)

print("Precision :", precision)
print("Recall    :", recall)
print("F1 Score  :", f1)
print("Accuracy  :", accuracy)
print("ROC-AUC   :", roc_auc)
print("Confusion Matrix:\n", conf_mat)

Precision : 0.080331342708534
Recall    : 0.556
F1 Score  : 0.14038040733883184
Accuracy  : 0.5642119634781124
ROC-AUC   : 0.5893625064575926
Confusion Matrix:
 [[6195 4774]
 [ 333  417]]


In [164]:
from sklearn.linear_model import LogisticRegression # i using l2 because it work like smote and not using l1 because it remove some rows 

ridge_model = LogisticRegression(
    penalty='l2',
    C=1.0,
    class_weight='balanced',
    max_iter=1000,
    solver='lbfgs'
)

ridge_model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,'balanced'
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [165]:
y_pred = ridge_model.predict(X_val)
y_prob = ridge_model.predict_proba(X_val)[:, 1]

In [166]:
test_ridge = ridge_model.predict(data_test)
test_ridge = ridge_model.predict_proba(data_test)[:, 1]

In [167]:
from sklearn.metrics import (precision_score,recall_score,f1_score,accuracy_score,confusion_matrix,roc_auc_score)
precision = precision_score(y_val, y_pred)
recall    = recall_score(y_val, y_pred)
f1        = f1_score(y_val, y_pred)
accuracy  = accuracy_score(y_val, y_pred)
conf_mat  = confusion_matrix(y_val, y_pred)
roc_auc   = roc_auc_score(y_val, y_prob)

print("Precision :", precision)
print("Recall    :", recall)
print("F1 Score  :", f1)
print("Accuracy  :", accuracy)
print("ROC-AUC   :", roc_auc)
print("Confusion Matrix:\n", conf_mat)

Precision : 0.080331342708534
Recall    : 0.556
F1 Score  : 0.14038040733883184
Accuracy  : 0.5642119634781124
ROC-AUC   : 0.5893625064575926
Confusion Matrix:
 [[6195 4774]
 [ 333  417]]


In [168]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    max_depth=8,
    min_samples_leaf=50,
    class_weight='balanced',
    random_state=42
)

dt_model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,8
,min_samples_split,2
,min_samples_leaf,50
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,'balanced'


In [169]:
dt_pre = dt_model.predict(X_val)
dt_prob = dt_model.predict_proba(X_val)[:, 1]

In [170]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

print("Accuracy :", accuracy_score(y_val, dt_pre))
print("Precision:", precision_score(y_val, dt_pre))
print("Recall   :", recall_score(y_val, dt_pre))
print("F1 Score :", f1_score(y_val, dt_pre))
print("ROC-AUC  :", roc_auc_score(y_val, dt_prob))
print("Confusion Matrix:\n", confusion_matrix(y_val, dt_pre))

Accuracy : 0.5289700486389624
Precision: 0.0886512590548465
Recall   : 0.6853333333333333
F1 Score : 0.15699450213805743
ROC-AUC  : 0.6411988330750297
Confusion Matrix:
 [[5685 5284]
 [ 236  514]]


In [171]:
train_pre = dt_model.predict(X_train)
accuracy_train = accuracy_score(y_train,train_pre) 
accuracy_train

0.5331000789367013

In [172]:
X = data_train.drop('is_claim', axis=1)
y = data_train['is_claim']
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [173]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    min_samples_leaf=50,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

,n_estimators,200
,criterion,'gini'
,max_depth,12
,min_samples_split,2
,min_samples_leaf,50
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [174]:
rf_pred = rf_model.predict(X_val)
rf_prob = rf_model.predict_proba(X_val)[:, 1]

In [175]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

print("Accuracy :", accuracy_score(y_val, rf_pred))
print("Precision:", precision_score(y_val, rf_pred))
print("Recall   :", recall_score(y_val, rf_pred))
print("F1 Score :", f1_score(y_val, rf_pred))
print("ROC-AUC  :", roc_auc_score(y_val, rf_prob))
print("Confusion Matrix:\n", confusion_matrix(y_val, rf_pred))

Accuracy : 0.6340131410529909
Precision: 0.10065447980139923
Recall   : 0.5946666666666667
F1 Score : 0.17216753522486006
ROC-AUC  : 0.6562894217035887
Confusion Matrix:
 [[6984 3985]
 [ 304  446]]


In [176]:
from sklearn.ensemble import RandomForestClassifier

rf_base = RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

In [177]:
param_dist = {
    'n_estimators': [200, 300, 400, 500],
    'max_depth': [8, 10, 12, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [20, 30, 50, 100],
    'max_features': ['sqrt', 'log2']
}

In [178]:
from sklearn.model_selection import RandomizedSearchCV

rf_random = RandomizedSearchCV(
    estimator=rf_base,
    param_distributions=param_dist,
    n_iter=25,
    scoring='roc_auc',
    cv=3,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

In [179]:
rf_random.fit(X_train, y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits


,estimator,RandomForestC...ndom_state=42)
,param_distributions,"{'max_depth': [8, 10, ...], 'max_features': ['sqrt', 'log2'], 'min_samples_leaf': [20, 30, ...], 'min_samples_split': [2, 5, ...], ...}"
,n_iter,25
,scoring,'roc_auc'
,n_jobs,-1
,refit,True
,cv,3
,verbose,1
,pre_dispatch,'2*n_jobs'
,random_state,42
,error_score,nan


In [181]:
print("Best Parameters:", rf_random.best_params_)
print("Best CV ROC-AUC:", rf_random.best_score_)

Best Parameters: {'n_estimators': 400, 'min_samples_split': 5, 'min_samples_leaf': 50, 'max_features': 'sqrt', 'max_depth': 8}
Best CV ROC-AUC: 0.6471607706395854


In [183]:
best_rf = rf_random.best_estimator_
best_rf

,n_estimators,400
,criterion,'gini'
,max_depth,8
,min_samples_split,5
,min_samples_leaf,50
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [184]:
final_rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

final_rf.fit(X, y)

,n_estimators,300
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [185]:
test_preds = final_rf.predict(data_test)
test_probs = final_rf.predict_proba(data_test)[:, 1]

In [186]:
neg, pos = y.value_counts()
scale_pos_weight = neg / pos
scale_pos_weight

14.632870864461045

In [187]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    objective='binary:logistic',
    eval_metric='auc',
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

,objective,'binary:logistic'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,0.8
,device,None
,early_stopping_rounds,None
,enable_categorical,False
,eval_metric,'auc'


In [188]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

y_val_pred = xgb_model.predict(X_val)
y_val_prob = xgb_model.predict_proba(X_val)[:, 1]

print("Accuracy :", accuracy_score(y_val, y_val_pred))
print("Precision:", precision_score(y_val, y_val_pred))
print("Recall   :", recall_score(y_val, y_val_pred))
print("F1 Score :", f1_score(y_val, y_val_pred))
print("ROC-AUC  :", roc_auc_score(y_val, y_val_prob))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))

Accuracy : 0.6556873453366329
Precision: 0.09534368070953436
Recall   : 0.516
F1 Score : 0.16094822208359327
ROC-AUC  : 0.633260643632054
Confusion Matrix:
 [[7297 3672]
 [ 363  387]]


In [189]:
xgb_model.fit(X, y)

test_preds_xgb = xgb_model.predict(data_test)
test_probs_xgb = xgb_model.predict_proba(data_test)[:, 1]

In [192]:
from lightgbm import LGBMClassifier

lgb_model = LGBMClassifier(
    n_estimators=400,
    max_depth=-1,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

lgb_model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 2998, number of negative: 43875
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008773 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 496
[LightGBM] [Info] Number of data points in the train set: 46873, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000


,boosting_type,'gbdt'
,num_leaves,31
,max_depth,-1
,learning_rate,0.05
,n_estimators,400
,subsample_for_bin,200000
,objective,None
,class_weight,'balanced'
,min_split_gain,0.0
,min_child_weight,0.001
,min_child_samples,20


In [191]:
pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   -------------- ------------------------- 0.5/1.5 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 4.4 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\sande\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [193]:
y_val_pred = lgb_model.predict(X_val)
y_val_prob = lgb_model.predict_proba(X_val)[:, 1]

print("Accuracy :", accuracy_score(y_val, y_val_pred))
print("Precision:", precision_score(y_val, y_val_pred))
print("Recall   :", recall_score(y_val, y_val_pred))
print("F1 Score :", f1_score(y_val, y_val_pred))
print("ROC-AUC  :", roc_auc_score(y_val, y_val_prob))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))

Accuracy : 0.649458144892909
Precision: 0.09794061302681992
Recall   : 0.5453333333333333
F1 Score : 0.1660576532683719
ROC-AUC  : 0.6422254839395873
Confusion Matrix:
 [[7202 3767]
 [ 341  409]]


In [194]:
lgb_model.fit(X, y)

test_preds_lgb = lgb_model.predict(data_test)
test_probs_lgb = lgb_model.predict_proba(data_test)[:, 1]

[LightGBM] [Info] Number of positive: 3748, number of negative: 54844
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008140 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 500
[LightGBM] [Info] Number of data points in the train set: 58592, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000


In [195]:
y_val_prob = lgb_model.predict_proba(X_val)[:,1]
y_val_pred = (y_val_prob >= 0.3).astype(int)

In [196]:
import pickle
with open("lightgbm_claim_model.pkl", "wb") as f:
    pickle.dump(lgb_model, f)

In [197]:
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

In [198]:
feature_names = X.columns.tolist()

with open("feature_names.pkl", "wb") as f:
    pickle.dump(feature_names, f)

In [199]:
from sklearn.model_selection import RandomizedSearchCV
import lightgbm as lgb

lgb_model = lgb.LGBMClassifier(
    objective='binary',
    class_weight='balanced',
    random_state=42
)

param_dist = {
    'num_leaves': [15, 31, 63],
    'max_depth': [5, 8, 10],
    'learning_rate': [0.01, 0.05, 0.1],
    'n_estimators': [200, 400, 600]
}

random_search = RandomizedSearchCV(
    lgb_model,
    param_distributions=param_dist,
    n_iter=10,
    scoring='roc_auc',
    cv=3,
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

print("Best params:", random_search.best_params_)
print("Best CV ROC-AUC:", random_search.best_score_)

[LightGBM] [Info] Number of positive: 2998, number of negative: 43875
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006272 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 496
[LightGBM] [Info] Number of data points in the train set: 46873, number of used features: 26
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
Best params: {'num_leaves': 15, 'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.01}
Best CV ROC-AUC: 0.6509307518116408


In [200]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    scale_pos_weight=scale_pos_weight,
    random_state=42
)

param_dist = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'n_estimators': [200, 400, 600],
    'subsample': [0.7, 0.9, 1.0]
}

random_search = RandomizedSearchCV(
    xgb_model,
    param_dist,
    n_iter=10,
    scoring='roc_auc',
    cv=3,
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

,estimator,"XGBClassifier...ree=None, ...)"
,param_distributions,"{'learning_rate': [0.01, 0.05, ...], 'max_depth': [3, 5, ...], 'n_estimators': [200, 400, ...], 'subsample': [0.7, 0.9, ...]}"
,n_iter,10
,scoring,'roc_auc'
,n_jobs,-1
,refit,True
,cv,3
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,42
,error_score,nan


In [201]:
print("Best params:", random_search.best_params_)
print("Best CV ROC-AUC:", random_search.best_score_)

Best params: {'subsample': 0.7, 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.01}
Best CV ROC-AUC: 0.6512075895382562


In [180]:
# submission = pd.DataFrame({
#     'policy_id': test_policy_id,
#     'is_claim': test_preds
# })